### ISSUE TITLE
Classic only or Release too

### ISSUE THREAD

**Issue by Enigma-TL** [Dreamwalker-Collective/faction-friend#34]
I have been having big problems with FFriend in Release and was wondering is this only for classic or does it cover release too?

**Comment by ShaunaGordon** [comment]
It's only for Classic. Unfortunately, due to the nature of the changes that have been made in Retail, I don't think I'll be able to get FactionFriend working there.

However, I am in the process of a ground-up rewrite intended for Retail, though I don't have a release date for it yet.

**Comment by Enigma-TL** [comment]
BOOOOO...  Well here's hoping you get the retail version done with little problems.  This is one of my favorite addons but its now causing lots of problems in retail.  THX for keeping it alive.
